name: Build
on: [push]
jobs:

  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    steps:

    - name: Set up Go 1.20
      uses: actions/setup-go@v3
      with:
        go-version: 1.20
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v3

    - name: Build
      run: go build -o go-gvacli -v .

    - name: Save artifacts
      uses: actions/upload-artifact@v3
      with:
        name: go-gvacli-${{ matrix.os }}
        path: go-gvacli
