name: Build
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: [ 'darwin', 'windows', 'linux' ]
    steps:

    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1
      
    - name: Build for ${{ matrix.target }}
      env:
        GOOS: ${{ matrix.target }}
        GOARCH: amd64
      run: go build -o go-gvacli_$GOOS_$GOARCH -v .
      
    - name: Save artifacts
      uses: actions/upload-artifact@v1
      with:
        name: go-gvacli-${{ matrix.os }}
        path: go-gvacli_*
