name: Build
on: [push]
jobs:

  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    steps:

    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1
      
    - name: Build
      run: go build -v .

  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Release
        uses: fnkr/github-action-ghr@v1
        if: startsWith(github.ref, 'refs/tags/v')
        env:
          GHR_COMPRESS: xz
          GHR_PATH: go-gvacli
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
